from __future__ import annotations

HISTORICAL_RESEARCH = "HISTORICAL_RESEARCH"
BACKTEST_RESEARCH = "BACKTEST_RESEARCH"
LIVE_INTRADAY_DIAGNOSTIC = "LIVE_INTRADAY_DIAGNOSTIC"
OPERATOR_REPLAY_DIAGNOSTIC = "OPERATOR_REPLAY_DIAGNOSTIC"

ALLOWED_RUNTIME_CONTEXTS = {
    HISTORICAL_RESEARCH,
    BACKTEST_RESEARCH,
    LIVE_INTRADAY_DIAGNOSTIC,
    OPERATOR_REPLAY_DIAGNOSTIC,
}

LIVE_CONTEXTS = {LIVE_INTRADAY_DIAGNOSTIC, OPERATOR_REPLAY_DIAGNOSTIC}
HISTORICAL_CONTEXTS = {HISTORICAL_RESEARCH, BACKTEST_RESEARCH}


def require_runtime_context(value: str) -> str:
    context = str(value or "").strip().upper()
    if context not in ALLOWED_RUNTIME_CONTEXTS:
        raise ValueError(f"runtime_context must be one of {sorted(ALLOWED_RUNTIME_CONTEXTS)}")
    return context
