"""Build Task3852 read-only paper gate dependency DAG artifacts."""

from __future__ import annotations

import csv
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


TASK_ID = "task_3852_paper_gate_dependency_dag"
PREV_TASK_ID = "task_3845_source_authority_gate_10_loop"
ARTIFACT_DIR = Path("data/artifacts") / TASK_ID
REPORT_DIR = Path("docs/reports") / TASK_ID
PREV_ARTIFACT_DIR = Path("data/artifacts") / PREV_TASK_ID

NODES_PATH = ARTIFACT_DIR / "paper_gate_dependency_nodes.csv"
EDGES_PATH = ARTIFACT_DIR / "paper_gate_dependency_edges.csv"
STATE_PATH = ARTIFACT_DIR / "paper_gate_dependency_dag_state.json"
REPORT_PATH = REPORT_DIR / "paper_gate_dependency_dag_report.md"
MANIFEST_PATH = REPORT_DIR / "artifact_manifest.csv"

HARD_STATE = {
    "strategy": "NOT_ACCEPTED",
    "deployment": "DIAGNOSTIC_ONLY_NOT_DEPLOYMENT_READY",
    "real_capital": "FORBIDDEN",
}


def utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def build_nodes(paper_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    nodes = [
        {
            "node_id": "paper_gate_root",
            "node_type": "root_gate",
            "label": "paper/live permission",
            "status": "BLOCKED",
            "permission_granted": "false",
            "notes": "Paper/live permission is forbidden unless future governance explicitly changes it.",
        }
    ]
    for row in paper_rows:
        nodes.append(
            {
                "node_id": row.get("gate_id", ""),
                "node_type": "dependency_gate",
                "label": row.get("gate", ""),
                "status": row.get("status", "BLOCKED"),
                "permission_granted": "false",
                "notes": row.get("notes", ""),
            }
        )
    return nodes


def build_edges(paper_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    edges = []
    for row in paper_rows:
        edges.append(
            {
                "edge_id": f"edge-{row.get('gate_id', '')}",
                "from_node": row.get("gate_id", ""),
                "to_node": "paper_gate_root",
                "dependency_type": "must_clear_before_root",
                "current_status": row.get("status", "BLOCKED"),
                "weakest_link_blocks_root": "true",
                "inference_allowed": "false",
            }
        )
    return edges


def build_manifest() -> list[dict[str, str]]:
    paths = [NODES_PATH, EDGES_PATH, STATE_PATH, REPORT_PATH, MANIFEST_PATH]
    return [
        {
            "artifact_path": path.as_posix(),
            "artifact_type": "report" if path.suffix == ".md" else path.suffix.lstrip("."),
            "authority": "DIAGNOSTIC_ONLY_NOT_AUTHORITY",
            "status": "active",
            "notes": "Generated by Task3852 read-only paper gate dependency DAG.",
        }
        for path in paths
    ]


def write_report(state: dict[str, Any], nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Task3852 Paper Gate Dependency DAG",
        "",
        "## Summary",
        "",
        "This task maps paper/live permission blockers as a dependency DAG.",
        "It does not grant paper/live permission and does not create order intents or broker actions.",
        "",
        "## Hard State",
        "",
        f"- Strategy: {HARD_STATE['strategy']}",
        f"- Deployment: {HARD_STATE['deployment']}",
        f"- Real capital: {HARD_STATE['real_capital']}",
        "- Paper/live permission: FORBIDDEN",
        "",
        "## Root Gate",
        "",
        "- `paper_gate_root` remains `BLOCKED`.",
        "- Every dependency edge blocks the root until separately proven by future authority.",
        "",
        "## Outputs",
        "",
        f"- Nodes: `{NODES_PATH.as_posix()}`",
        f"- Edges: `{EDGES_PATH.as_posix()}`",
        "",
        "## Safety",
        "",
        "- No paper order, live order, order intent, broker mutation, deployment readiness, strategy acceptance, or real-capital permission is granted.",
        "- Missing/stale evidence remains `UNKNOWN/BLOCKER`.",
        "- Composite paper gate status cannot exceed the weakest dependency.",
        "",
        "## State",
        "",
        f"- Node rows: {len(nodes)}",
        f"- Edge rows: {len(edges)}",
        f"- Permission granted rows: {state['permission_granted_rows']}",
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    paper_rows = read_csv(PREV_ARTIFACT_DIR / "paper_gate_blocker_matrix.csv")
    if not paper_rows:
        raise SystemExit("Task3845 paper gate blocker matrix is missing or empty.")
    nodes = build_nodes(paper_rows)
    edges = build_edges(paper_rows)
    state = {
        "task_id": TASK_ID,
        "previous_task_id": PREV_TASK_ID,
        "generated_at_utc": utc_now(),
        **HARD_STATE,
        "overall_status": "READ_ONLY_PAPER_GATE_DAG_COMPLETE_WITH_BLOCKERS",
        "node_row_count": len(nodes),
        "edge_row_count": len(edges),
        "permission_granted_rows": sum(1 for row in nodes if row["permission_granted"] != "false"),
        "source_acquisition_run": False,
        "scheduler_run": False,
        "db_mutation": False,
        "broker_mutation_added": False,
        "paper_live_permission_granted": False,
        "real_capital_permission_granted": False,
    }
    write_csv(NODES_PATH, nodes, ["node_id", "node_type", "label", "status", "permission_granted", "notes"])
    write_csv(EDGES_PATH, edges, ["edge_id", "from_node", "to_node", "dependency_type", "current_status", "weakest_link_blocks_root", "inference_allowed"])
    write_json(STATE_PATH, state)
    write_report(state, nodes, edges)
    write_csv(MANIFEST_PATH, build_manifest(), ["artifact_path", "artifact_type", "authority", "status", "notes"])
    print(json.dumps(state, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
