from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "data" / "frontend_snapshots" / "current_backtest_snapshot.json"
TS_FIXTURE = ROOT / "apps" / "ios-trader-brain" / "src" / "read-models" / "backtestSnapshotFixture.ts"
HOME_ROUTE = ROOT / "apps" / "ios-trader-brain" / "app" / "(tabs)" / "index.tsx"
RUNNER = ROOT / "scripts" / "run_task3903_stage1_sec_neutral_attach_same_experiment_replay.py"


def fail(failures: list[str], message: str) -> None:
    failures.append(message)


def main() -> None:
    failures: list[str] = []
    for path in [SNAPSHOT, TS_FIXTURE, HOME_ROUTE, RUNNER]:
        if not path.exists():
            fail(failures, f"missing required file: {path.relative_to(ROOT).as_posix()}")
    if failures:
        for failure in failures:
            print(f"[FRONTEND_BACKTEST_SNAPSHOT_ERROR] {failure}")
        sys.exit(1)

    snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    fixture = TS_FIXTURE.read_text(encoding="utf-8")
    home = HOME_ROUTE.read_text(encoding="utf-8")
    runner = RUNNER.read_text(encoding="utf-8")

    expected = {
        "contractVersion": "frontend-backtest-snapshot-v1",
        "snapshotType": "READ_ONLY_SELECTED_BACKTEST_SNAPSHOT",
        "authority": "NOT_AUTHORITY",
        "displayState": "DIAGNOSTIC_ONLY",
        "selectedTaskId": "Task3903",
    }
    for key, value in expected.items():
        if snapshot.get(key) != value:
            fail(failures, f"snapshot {key} must be {value}")

    governance = snapshot.get("governance", {})
    if governance.get("strategyAcceptance") != "NOT_ACCEPTED":
        fail(failures, "strategy acceptance changed")
    if governance.get("deploymentReadiness") != "DIAGNOSTIC_ONLY_NOT_DEPLOYMENT_READY":
        fail(failures, "deployment readiness changed")
    if governance.get("realCapital") != "FORBIDDEN":
        fail(failures, "real capital changed")
    if governance.get("brokerMutationPermitted") is not False:
        fail(failures, "broker mutation must remain false")
    if governance.get("paperPermission") is not False:
        fail(failures, "paper permission must remain false")
    if governance.get("livePermission") is not False:
        fail(failures, "live permission must remain false")

    equity_curve = snapshot.get("equityCurve", [])
    if len(equity_curve) < 10:
        fail(failures, "equity curve must be attached for frontend display")
    diagnostic_positions = snapshot.get("diagnosticPositions", [])
    if len(diagnostic_positions) < 3:
        fail(failures, "diagnostic positions must be attached for portfolio display")
    if diagnostic_positions and not isinstance(diagnostic_positions[0].get("totalPnl"), (int, float)):
        fail(failures, "diagnostic positions must expose numeric totalPnl")
    if snapshot.get("chartSource", {}).get("status") != "READY":
        fail(failures, "chart source must be READY after equity curve attachment")
    if snapshot.get("metrics", {}).get("finalEquity") != 6537.58:
        fail(failures, "unexpected selected final equity")
    if snapshot.get("selectedPolicy", {}).get("policyId") != "exit_chain_repaired_soft_boost_cap_top2_v1":
        fail(failures, "unexpected selected policy")

    for term in [
        "AUTO-GENERATED by scripts/build_frontend_backtest_snapshot.py",
        f'"generatedAt": "{snapshot["generatedAt"]}"',
        '"equityCurve": [',
        '"diagnosticPositions": [',
    ]:
        if term not in fixture:
            fail(failures, f"fixture missing generated term: {term}")

    for term in ["backtestSnapshotFixture", "백테스트 진단", "진단 전용", "전략 승인이나 실제 계좌 성과가 아닙니다"]:
        if term not in home:
            fail(failures, f"HOME route missing visible backtest display term: {term}")

    for term in ["build_frontend_backtest_snapshot", "TASK3903_FRONTEND_BACKTEST_SNAPSHOT_UPDATED"]:
        if term not in runner:
            fail(failures, f"Task3903 runner missing auto-refresh hook: {term}")

    forbidden = ["trading.db", "brokerSubmit", "submitOrder", "placeOrder", "sendLiveOrder"]
    for term in forbidden:
        if term in fixture or term in home:
            fail(failures, f"forbidden frontend term found: {term}")

    if failures:
        for failure in failures:
            print(f"[FRONTEND_BACKTEST_SNAPSHOT_ERROR] {failure}")
        sys.exit(1)

    print(
        "[FRONTEND_BACKTEST_SNAPSHOT_OK] "
        f"task={snapshot['selectedTaskId']} policy={snapshot['selectedPolicy']['policyId']} "
        f"equity_points={len(equity_curve)} final={snapshot['metrics']['finalEquity']}"
    )
    print("Test results do not modify strategy acceptance status.")
    print("Strategy: NOT_ACCEPTED")
    print("Deployment: DIAGNOSTIC_ONLY_NOT_DEPLOYMENT_READY")
    print("Real Capital: FORBIDDEN")


if __name__ == "__main__":
    main()
